### PR TITLE
Biosample_unlinking - Upgraded unlinking features and fixed code

### PR DESCRIPTION
**Pull request by M-casado**
Continuation of the PR https://github.com/enasequence/ena-content-dataflow/pull/15, to which I have no authority of contribution. 

I changed the code quite a bit: fixed, clean, and containerized it as much as I could. Please @z-w123 review the changes if you see it fit and, more importantly, test that it works (I still receive the same Java issue I had in the past).

### CODE REVIEW

**Comment by z-w123** [comment]
Thanks for working on this! I can confirm the script is functioning properly and also resolves the issue with repeated source accessions, which is great

**Comment by z-w123** [comment]
Just something I have noticed:

- If the target accession is incorrect, and does not point to a real biosample, the source->target relationship is still added to the source biosample. E.g. https://wwwdev.ebi.ac.uk/biosamples/samples/SAMEA8785882 . The correct target accession should be SAMEA8123975, instead of SAMEA812397555 which leads to a 404 Biosamples error). 

Again, though I think this is fine for now,  in the future I think it would be useful to have an additional feature where the script can identify invalid target accessions from the spreadsheet (which could occur due to a typo), and prevent them from being added to the json file in the first place. We could use a get request to see if the target accession is valid.

**Comment by z-w123** [comment]
-Whereas if there is an error with the source accession, the script does not run at all, so at least we know the accession is invalid in this way. Though would be good to have the script continue to run for the rest of the source samples in the file instead

**Comment by z-w123** [comment]
Would be good to get your thoughts on the above. But will merge this PR.

**Comment by M-casado** [comment]
> If the target accession is incorrect, and does not point to a real biosample, the source->target relationship is still added to the source biosample. E.g. https://wwwdev.ebi.ac.uk/biosamples/samples/SAMEA8785882 . The correct target accession should be SAMEA8123975, instead of SAMEA812397555 which leads to a 404 Biosamples error).

The first filter we could implement is a **regular expression** for these accessions to match. That way we would avoid adding typing errors as accessions. The only issue I found is that accessions in BioSamples do not follow constraints regarding the numbers that follow the text keys:

> _BioSample accessions always begin with SAM. The next letter is either E or N or D depending if the sample information was originally submitted to EMBL-EBI or NCBI or DDBJ respectively. After that, there may be an A or a G to denote an Assay sample or a Group of samples. Finally there is a numeric component that may or may not be zero-padded._

So this alternative would not solve the example you cited. But then again, it may still be useful to avoid incorrect requests. 
> Though would be good to have the script continue to run for the rest of the source samples in the file instead of stopping at the first 'incorrect' source accession.

I agree, although for now the script would still be convenient, since repeated source-target pairs are avoided if I remember correctly. So restarting the script from the beginning would not alter the result if the script stops mid-way. 

> We could use a get request to see if the target accession is valid.

I'm okay with this, my only concerns are:
* The time that it may take for it to check every source and every target. But it definitely can be done. 
* How that request method would handle accessions that do exist but are private (error 403 if I remember correctly).

**Comment by z-w123** [comment]
> The first filter we could implement is a **regular expression** for these accessions to match.

I agree that regular expression might still be useful - I can try and find out more information from the Biosamples team regarding their accessioning later/ when needed.

> I agree, although for now the script would still be convenient, since repeated source-target pairs are avoided if I remember correctly

Yes at least for the viral <> human data there should not be repeat sources

> * The time that it may take for it to check every source and every target. But it definitely can be done.
> * How that request method would handle accessions that do exist but are private (error 403 if I remember correctly).

Hmm regarding the private samples, I would have to test this to double check. Though good reminder that our script would not support linking of any private data

**Pull request merged**
